# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Link
  description: 
  preview:
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  link_text:
  link_url:
  open_in_new_tab:



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  link_text:
    type: text
  link_url:
    type: text
  open_in_new_tab:
    type: boolean