collections_config:
  pages:
    _enabled_editors:
      - visual
  collections:
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/collection.md
  blog:
    _enabled_editors:
      - content
      - visual
_inputs:
  content:
    type: markdown
  icon:
    type: select
    options:
      values:
        - ph-user-square
  description:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  collection_content:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  collection_cover:
    type: image
  collection_cover_mobile:
    type: image
  collection_preview:
    type: array
  collection_preview[*]:
    type: image
  isActive:
    type: switch
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
  quote:
    type: text
  image:
    type: image
  align_y:
    type: select
    options:
      values:
        - start
        - center
        - end
  align_x:
    type: select
    options:
      values:
        - start
        - center
        - end
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  margin_left:
    type: range
    options:
      step: 5
      max: 100
      min: 0
  margin_y:
    label: Margin Top
    type: range
    options:
      step: 50
      max: 1000
      min: -50
  caption:
    type: text
  color: 
    type: color
  theme_color: 
    type: color
  theme_color_all_work: 
    type: color
  logo:
    type: image
  row_alignment:
    type: select
    options:
      values:
        - start
        - center
        - end
        - between
        - around
  collection_description_alignment:
    type: select
    options:
      values:
        - left
        - center
        - right
  collection_category:
    type: multiselect
    options:
      values:
        - Portraits
        - Environments
        - Still Life + Details
        - Sports + Athletes
        - Humor
        - Conceptual
        - Lifestyle
        - Workplace
        - Color
        - Black and White
        - Climate Change
        - Travel
        - Reportage
        - Motion
        - Tech
        - Science
        - Editorial
        - Advertising
        - Stock
        - Studio
        - Exhibited Works
        - Award Winning
        - Kids


_structures:
  features:
    values:
      - value: 
          item: 
          isActive: 

_editables:
  text:

