collections_config:
  pages:
    _enabled_editors:
      - visual
  collections:
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/collection.md
    preview:
      gallery:
        image:
          - key: collection_cover
        fit: cover
      text:
        - key: title
      subtext:
        - key: slug
  blog:
    _enabled_editors:
      - content
      - visual
  posts:
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/posts.md
  overview:
    _enabled_editors:
      - visual
    schemas:
      default:
        path: schemas/overview.md
  shop:
    _enabled_editors:
      - visual
    preview:
      gallery:
        image:
          - key: collection_preview
        fit: cover 
      text:
        - key: title
      subtext:
        - key: price
_inputs:
  content:
    type: markdown
  title: 
    type: text
  text:
    type: markdown
  icon:
    type: image
  url:
    type: text
  description:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  about_bio:
    type: markdown
  feature_description:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  overview_collection:
    type: array
  overview_collection[*]:
    type: select
    options:
      values: collections.collections
  collection_content:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  collection_cover:
    type: image
  collection_cover_mobile:
    type: image
  collection_preview:
    type: array
  collection_preview[*]:
    type: image
  attached:
    type: switch
  blog_block_cover:
    type: image
  isActive:
    type: switch
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
  quote:
    type: text
  image:
    type: image
  image_mobile:
    type: image
  align_y:
    type: select
    options:
      values:
        - 'start'
        - 'center'
        - 'end'
  align_x:
    type: select
    options:
      values:
        - 'start'
        - 'center'
        - 'end'
  width:
    type: select
    options:
      values:
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '33'
        - '35'
        - '40'
        - '45'
        - '50'
        - '55'
        - '60'
        - '65'
        - '66'
        - '70'
        - '75'
        - '80'
        - '85'
        - '90'
        - '95'
        - '100'
  margin_right:
    type: select
    options:
      values:
        - '5'
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '35'
        - '40'
        - '45'
        - '50'
        - '55'
        - '60'
        - '65'
        - '70'
        - '75'
        - '80'
        - '85'
        - '90'
        - '95'
        - '100'
        - '0'
  margin_left:
    type: select
    options:
      values:
        - '5'
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '35'
        - '40'
        - '45'
        - '50'
        - '55'
        - '60'
        - '65'
        - '70'
        - '75'
        - '80'
        - '85'
        - '90'
        - '95'
        - '100'
        - '0'
  margin_y:
    label: Margin Top
    type: select
    options:
      values:
        - '-250'
        - '-200'
        - '-150'
        - '-100'
        - '-50'
        - '50'
        - '100'
        - '150'
        - '200'
        - '250'
        - '300'
        - '350'
        - '400'
        - '450'
        - '500'
        - '550'
        - '600'
        - '650'
        - '700'
        - '750'
        - '800'
        - '850'
        - '900'
        - '950'
        - '1000'
        - '0'
  title_margin_left:
    type: select
    options:
      values:
        - '-5'
        - '-10'
        - '-15'
        - '-20'
        - '-25'
        - '-30'
        - '-35'
        - '-40'
        - '-45'
        - '-50'
        - '-55'
        - '-60'
        - '-65'
        - '-70'
        - '-75'
        - '-80'
        - '-85'
        - '-90'
        - '-95'
        - '-100'
        - '5'
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '35'
        - '40'
        - '45'
        - '50'
        - '55'
        - '60'
        - '65'
        - '70'
        - '75'
        - '80'
        - '85'
        - '90'
        - '95'
        - '100'
        - '0'
  title_margin_y:
      label: Title Margin Top
      type: select
      options:
        values:
          - '0'
          - '5'
          - '10'
          - '15'
          - '20'
          - '25'
          - '30'
          - '35'
          - '40'
          - '45'
          - '50'
          - '55'
          - '60'
          - '65'
          - '70'
          - '75'
          - '80'
          - '85'
          - '90'
          - '95'
          - '100'
          - '-5'
          - '-10'
          - '-15'
          - '-20'
          - '-25'
          - '-30'
          - '-35'
          - '-40'
          - '-45'
          - '-50'
          - '-55'
          - '-60'
          - '-65'
          - '-70'
          - '-75'
          - '-80'
          - '-85'
          - '-90'
          - '-95'
          - '-100'
  title_margin_right:
    type: select
    options:
      values:
        - '-25'
        - '5'
        - '10'
        - '15'
        - '20'
        - '25'
        - '30'
        - '35'
        - '40'
        - '45'
        - '50'
        - '55'
        - '60'
        - '65'
        - '70'
        - '75'
        - '80'
        - '85'
        - '90'
        - '95'
        - '100'
        - '0'
  vimeo_id:
    type: number
  vimeo_block_cover:
    type: number
  show_controls:
    type: switch
  block_aspect_ratio:
    type: select
    options:
      values:
        - '8-5x11'
        - '11x8-5'
        - '9x16'
        - '16x9'
        - '5x4'
        - '4x5'
        - '4x3'
        - '3x4'
        - '2x3'
        - '3x2'
        - '1x2'
        - '1x1'
  caption:
    type: text
  color: 
    type: color
  theme_color: 
    type: color
  theme_color_all_works: 
    type: color
  text_color:
    type: color
  text_size:
    type: select
    options:
      values:
        - xs
        - sm
        - base
        - lg
        - xl
        - 2xl
        - 4xl
        - 6xl
        - 7xl
        - 8xl
        - 9xl
        - 10xl
  line_height:
    type: select
    options:
      values:
        - none
        - tight
        - snug
        - normal
        - relaxed
        - loose
  text_alignment:
    type: select
    options:
      values:
        - left
        - center
        - right
  text_tracking:
    type: select
    options:
      values:
        - tighter
        - tight
        - normal
        - wide
        - wider
        - widest
  font_weight:
    type: select
    options:
      values:
        - hairline
        - light
        - normal
        - semibold
        - bold
        - extrabold
  meta_align:
    type: select
    options:
      values:
        - left
        - center
        - right
  logo:
    type: image
  row_alignment:
    type: select
    options:
      values:
        - start
        - center
        - end
        - between
        - around
  collection_meta:
    type: text
  collection_meta_2:
    type: text
  collection_description:
    type: markdown
  collection_description_alignment:
    type: select
    options:
      values:
        - left
        - center
        - right
  collection_category:
    type: multiselect
    options:
      values: data.categories
  collection_filter:
    type: select
    options:
      values:
        - Commissioned + Stock
        - Personal
  collection_awards:
    type: array
  collection_awards[*]:
    type: markdown
  collection_press:
    type: array
  collection_press[*]:
    type: markdown
  collection_exhibition:
    type: array
  collection_exhibition[*]:
    type: markdown
  navigation_theme:
    type: select
    options:
      values:
        - white
        - black
  header_col_1_title:
    type: text
  header_col_1:
    type: html
  header_col_2_title:
    type: text
  header_col_2:
    type: html
  header_col_3_title:
    type: text
  header_col_3:
    type: html
  collection_pager:
    type: multiselect
    options:
      values: collections.collections
      value_key: content_path
  collection_sorter:
    type: multiselect
    options:
      values: collections.collections
      value_key: content_path  
  shop_sorter:
    type: multiselect
    options:
      values: collections.shop
      value_key: content_path  


_structures:
  features:
    values:
      - value: 
          item: 
          isActive: 

_editables:
  text:
  title:

