collections_config:
  pages:
    _enabled_editors:
      - visual
  collections:
    _enabled_editors:
      - visual
  blog:
    _enabled_editors:
      - content
      - visual
_inputs:
  content:
    type: markdown
  icon:
    type: select
    options:
      values:
        - ph-user-square
  description:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  collection_content:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  collection_cover:
    type: image
  collection_cover_mobile:
    type: image
  collection_preview:
    type: array
  collection_preview[*]:
    type: image
  isActive:
    type: switch
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
  quote:
    type: text
  image_file:
    type: image
  align_y:
    type: select
    options:
      values:
        - start
        - center
        - end
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  margin_left:
    type: range
    options:
      step: 5
      max: 100
      min: 0
  margin_y:
    label: Margin Top
    type: range
    options:
      step: 50
      max: 1000
      min: -50
  caption:
    type: text
  color: 
    type: color
  row_alignment:
    type: select
    options:
      values:
        - start
        - center
        - end
        - between
        - around


_structures:
  features:
    values:
      - value: 
          item: 
          isActive: 

