collections_config:
  pages:
    _enabled_editors:
      - visual
  collections:
    description: description test
    collection_meta: collection meta test
    collection_description: collection description test
    _enabled_editors:
      - visual
  blog:
    _enabled_editors:
      - content
      - visual
_inputs:
  content:
    type: markdown
  icon:
    type: select
    options:
      values:
        - ph-user-square
  description:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      removeformat: true
  collection_meta:
    type: text
  collection_description:
    type: text
  isActive:
    type: switch
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
_select_data:
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  margin_y:
    type: range
    options:
      step: 50
      max: 1000
      min: -50
  margin_left:
    type: range
    options:
      step: 5
      max: 100
      min: 100

_structures:
  features:
    values:
      - value: 
          item: 
          isActive: 

