baseURL = 'https://jesserieser.com'
languageCode = 'en-us'
title = 'Jesse Rieser'


[module]
replacements = "local/component-library -> ../component-library"

  [[module.imports]]
  path = 'local/component-library'

  [[module.imports]]
  path = 'github.com/cloudcannon/bookshop/hugo/v3'


[build]
  writeStats = true

[outputFormats.ContentOnly]
  name = "ContentOnly"
  mediaType = "text/html"
  isPlainText = true
  baseName = "content"
  noUgly = true