# Metadata about this component, to be used in the CMS
spec:
  structures:
    - post_blocks
  label: Motion ID
  description: Image element for collection gallery.
  preview:
    image:
      - key: image
    text:
      - key: caption
      - No Caption
    subtext:
      - key: width
  tags: ["posts"]

# Defines the structure of this component, as well as the default values
blueprint:
  video_id: 0
  show_controls: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  video_id:
    type: number
  show_controls:
    type: boolean
