# Metadata about this component, to be used in the CMS
spec:
  structures:
    - collection_blocks
  label: Text
  description:
  preview:

# Defines the structure of this component, as well as the default values
blueprint:
  text: insert text here
  background_color: "#000000"
  background_image_toggle: true
  image:
  text_color: "#000000"
  text_size: "lg"
  text_alignment: left
  text_tracking: normal
  font_weight: normal
  width: "50"
  align_y: start
  margin_y: "0"
  margin_left: "0"
  margin_right: "0"
  parallax: true
  image_css:
  caption_css:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  parallax:
    type: switch
  background_image_toggle:
    type: switch
  image_css:
    type: html
  caption_css:
    type: html
