# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Collection
  description:
  preview:
    image:
      - key: image
    text:
      - key: caption
    subtext:
      - key: width
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Collection Title" 
  meta: "Collection Meta"
  attached_collection: collections/xmas-in-america.md
  image: /images/hero/hero-image-2.png
  width: '40'
  margin_y: '0'
  margin_left: '0'
  margin_right: '0'
  align_y: center
  color: "#000000"
  caption: "test caption"
  title_margin_y: '0'
  title_margin_left: '0'
  title_margin_right: '0'
  text_size: 4xl
  text_color: "#000000"
  line_height: normal
  text_alignment: center
  text_tracking: normal
  font_weight: normal
  meta_align: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  attached_collection:
    type: select
    options:
      values: collections.collections
      value_key: content_path
      preview:
        text:
          - key: collection_meta
