# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Post
  description:
  preview:
    text:
      - key: title
      - No Caption
    subtext:
      - key: width
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Collection Title" 
  meta: "meta"
  attached_blog:
  text_size: base
  color: ffffff
  width: 30
  align_y: center
  margin_y: 0
  margin_left: 0
  margin_right: 0
  block_aspect_ratio: ratio-1x1
  blog_block_cover: https://d1sf55qlb7p6hz.cloudfront.net/retail_fresh-blog-1_minus2020.jpg
  caption: Caption
  theme_color: ff0000



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
  attached_blog:
    type: select
    options:
      values: collections.posts
      value_key: content_path
  align_y:
    type: select
    options:
      values:
        - start
        - center
        - end
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  margin_left:
    type: range
    options:
      step: 5
      max: 100
      min: 0
  margin_right:
    type: range
    options:
      step: 5
      max: 100
      min: 0
  margin_y:
    label: Margin Top
    type: range
    options:
      step: 50
      max: 1000
      min: -50
  color: 
    type: color
  theme_color: 
    type: color
  text_size:
    type: select
    options:
      values:
        - xs
        - sm
        - base
        - lg
        - xl
        - 2xl
        - 4xl
        - 6xl
        - 7xl
        - 8xl
        - 9xl
        - 10xl
  block_aspect_ratio:
    type: select
    options:
      values:
        - 8-5x11
        - 11x8-5
        - 9x16
        - 16x9
        - 5x4
        - 4x5
        - 4x3
        - 3x4
        - 2x3
        - 3x2
        - 1x2
