# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Post
  description:
  preview:
    image:
      - key: blog_block_cover
    text:
      - key: title
      - No Caption
    subtext:
      - key: width
  tags: ["blog"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Collection Title"
  caption: "Caption"
  attached_blog: posts/the-changing-landscape-of-american-retail-1.md
  blog_block_cover: https://d1sf55qlb7p6hz.cloudfront.net/retail_fresh-blog-1_minus2020.jpg
  vimeo_block_cover: 
  block_aspect_ratio: "1x1"
  text_size: "base"
  color: "#ffffff"
  width: "30"
  align_y: "center"
  margin_y: "0"
  margin_left: "0"
  margin_right: "0"
  meta_align: "left"
  theme_color: "#000000"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
  attached_blog:
    type: select
    options:
      values: collections.posts
      value_key: content_path
