# Metadata about this component, to be used in the CMS
spec:
  structures:
    - about_blocks
  label: List
  description: A popup list.
  preview:
    text:
      - key: title
      - No Caption
    subtext:
      - key: width
  tags: ["about"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: "List Title" 
  image: /images/hero/hero-image-2.png
  meta: "meta"
  text_size: base
  color: ffffff
  modal_color: ff0000
  text_color: ffffff
  width: '30'
  line_height: normal
  text_alignment: left
  text_tracking: normal
  font_weight: normal
  meta_align: left
  align_y: center
  margin_y: 0
  margin_left: 0
  margin_right: 0
  title_margin_y: 0
  title_margin_left: 0
  title_margin_right: 0



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
  attached_blog:
    type: select
    options:
      values: collections.blog
      value_key: content_path
  align_y:
    type: select
    options:
      values:
        - start
        - center
        - end
  color: 
    type: color
  text_size:
    type: select
    options:
      values:
        - xs
        - sm
        - base
        - lg
        - xl
        - 2xl
        - 4xl
        - 6xl
        - 7xl
        - 8xl
        - 9xl
        - 10xl
