# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Media Element
  description: media Element
  icon: "cottage"
  tags: ["coecction"]

# Defines the structure of this component, as well as the default values
blueprint:
  image_file: /images/hero/hero-image-2.png
  caption: test caption
  width: 50
  align_y: center
  margin_left: 50
  margin_y: 50
  color: "#ff0000"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_file:
    type: image
  align_y:
    type: select
    options:
      values:
        - start
        - center
        - end
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  margin_left:
    type: range
    options:
      step: 5
      max: 100
      min: 100
  margin_y:
    type: range
    options:
      step: 50
      max: 1000
      min: -50
  caption:
    type: text
  color: 
    type: color