# Metadata about this component, to be used in the CMS
spec:
  structures:
    - collection_blocks
  label: Media Element
  description: Image element for collection gallery.
  preview:
    image:
      - key: image
    text:
      - key: caption
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  image: /images/hero/hero-image-2.png
  width: 40
  margin_y: 0
  margin_left: 0
  margin_right: 0
  align_y: center
  color: "ff0000"
  caption: test caption

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image:
    - key: image
  text:
    - key: caption

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image:
    type: image
  align_y:
    type: select
    options:
      values:
        - start
        - center
        - end
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  margin_left:
    type: range
    options:
      step: 5
      max: 100
      min: 0
  margin_right:
    type: range
    options:
      step: 5
      max: 100
      min: 0
  margin_y:
    label: Margin Top
    type: range
    options:
      step: 50
      max: 1000
      min: -50
  caption:
    type: text
  color: 
    type: color