# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Media Element
  description: media Element
  icon: "cottage"
  tags: ["coecction"]

# Defines the structure of this component, as well as the default values
blueprint:
  image_file: /images/hero/hero-image-2.png


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_file:
    type: image
