# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Text
  description:
  preview:
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: link title
  meta: "meta"
  text_size: base
  align_y: center
  width: "33"
  margin_y: "0"
  margin_left: "0"
  margin_right: "0"
  block_aspect_ratio: "3x2"
  media:
  link:
  color: "#000000"
  text_color: "#ffffff"



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
