# Metadata about this component, to be used in the CMS
spec:
  structures:
    - post_blocks
  label: Media Element
  description: Image element for collection gallery.
  preview:
    image:
      - key: image
    text:
      - key: caption
      - No Caption
    subtext:
      - key: width
  tags: ["posts"]

# Defines the structure of this component, as well as the default values
blueprint:
  image: /images/hero/hero-image-2.png
  title: blog title
  caption: test caption
  width: 40

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image:
    type: image
  width:
    type: range
    options:
      step: 10
      max: 100
      min: 0
  title:
    type: text
  caption:
    type: text