# Metadata about this component, to be used in the CMS
spec:
  structures:
    - collection_blocks
  label: Media Row Full
  description: Media row
  icon: "vertical_distribute"
  tags: ["collection"]

# Defines the structure of this component, as well as the default values
blueprint:
  row_alignment: center
  media:
    image_file: /images/hero/hero-image-2.png


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  row_alignment:
    type: select
    options:
      values:
        - start
        - center
        - end
        - between
        - around
  media:
    type: object
    options:
      image_file:
        type: image
      caption:
        type: text